// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/12/2025, 9:46:19 PM
const configMerger = require("/Users/maurizianonnis/shadcn-project/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/maurizianonnis/shadcn-project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maurizianonnis/shadcn-project/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maurizianonnis/shadcn-project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maurizianonnis/shadcn-project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maurizianonnis/shadcn-project/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/maurizianonnis/shadcn-project/plugins/**/*.{js,ts,mjs}","/Users/maurizianonnis/shadcn-project/composables/**/*.{js,ts,mjs}","/Users/maurizianonnis/shadcn-project/utils/**/*.{js,ts,mjs}","/Users/maurizianonnis/shadcn-project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/maurizianonnis/shadcn-project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/maurizianonnis/shadcn-project/app.config.{js,ts,mjs}"] } }));

module.exports = config
